floreria/urls.py
from django.urls import path

from miTienda import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('registrar/', views.registrar_cliente, name='registrar_cliente'),
    path('login/', views.login_cliente, name='login_cliente'),
    path('logout/', views.logout_cliente, name='logout_cliente'),
    path('productos/', views.listar_productos, name='listar_productos'),
    path('agregar/', views.agregar_producto, name='agregar_producto'),
    path('crear_categoria/', views.crear_categoria, name='crear_categoria'),
    path('producto/borrar/<int:producto_id>/', views.borrar_producto, name='borrar_producto'),
    path('exportar_excel/', views.exportarExcel, name='exportar_excel'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miTienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('floreria.urls')),
]

floreria/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='productos/', blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre
    


class ClienteManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El correo electrónico es obligatorio')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class Cliente(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    direccion = models.TextField()
    telefono = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    objects = ClienteManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nombre', 'apellido']

    def __str__(self):
        return self.email
    
    @property
    def is_admin(self):
        return self.is_staff

floreria/forms.py
from django import forms
from .models import Producto, Categoria, Cliente

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'imagen', 'categoria']  # Incluye 'categoria'

        widgets = {
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido', 'email', 'direccion', 'telefono', 'password']

    password = forms.CharField(widget=forms.PasswordInput)
    
class LoginForm(forms.Form):
    username = forms.EmailField(label='Email', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    
from django import forms
from .models import Categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la categoría'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Descripción'}),
        }

floreria/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductoForm, ClienteForm, LoginForm, CategoriaForm
from .models import Producto, Categoria
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


@login_required
def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listar_productos')
    else:
        form = ProductoForm()

    return render(request, 'agregar_producto.html', {'form': form})

def index(request):
    return render(request, 'index.html')

def listar_productos(request):
    productos = Producto.objects.all()
    return render(request, 'listar_productos.html', {'productos': productos})

def registrar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_cliente')
    else:
        form = ClienteForm()
    return render(request, 'registrar_cliente.html', {'form': form})

def login_cliente(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')
                else:
                    form.add_error(None, 'Cuenta inactiva. Contacta al administrador.')
            else:
                form.add_error(None, 'Credenciales incorrectas.')
    else:
        form = LoginForm()
    return render(request, 'login_cliente.html', {'form': form})

def logout_cliente(request):
    logout(request)
    return redirect('index')

@login_required
def crear_categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agregar_producto')
    else:
        form = CategoriaForm()
    return render(request, 'crear_categoria.html', {'form': form})
@login_required
def borrar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    if request.method == 'POST':
        producto.delete()
        return redirect('listar_productos')
    return render(request, 'borrar_producto.html', {'producto': producto})

import xlwt
from django.http import HttpResponse
from .models import Producto  # Asegúrate de importar tu modelo Producto

def exportarExcel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=productos.xls'
    archivo = xlwt.Workbook(encoding='utf-8')
    hoja = archivo.add_sheet('Productos')
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columnas = ['ID', 'Nombre', 'Descripción', 'Precio', 'Categoría']
    for i in range(len(columnas)):
        hoja.write(0, i, columnas[i], font_style)

    productos = Producto.objects.all().values_list('id', 'nombre', 'descripcion', 'precio', 'categoria__nombre')
    
    row_num = 1
    for producto in productos:
        for i in range(len(producto)):
            hoja.write(row_num, i, producto[i], font_style)
        row_num += 1

    archivo.save(response)
    return response

floreria/templates/agregar_producto.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="form-container">
        <h1>Agregar Producto</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre</label>
                {{ form.nombre }}
            </div>
            <div class="form-group">
                <label for="id_descripcion">Descripción</label>
                {{ form.descripcion }}
            </div>
            <div class="form-group">
                <label for="id_precio">Precio</label>
                {{ form.precio }}
            </div>
            <div class="form-group">
                <label for="id_imagen">Imagen</label>
                {{ form.imagen }}
            </div>
            <div class="form-group">
                <label for="id_categoria">Categoría</label>
                {{ form.categoria }}
            </div>
            <button type="submit" class="btn btn-primary">Agregar Producto</button>
        </form>
    </div>
</div>
{% endblock %}

floreria/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Florería{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>Bienvenido a la Florería</h1>
        <nav>
            <ul>
                <li><a href="/">Inicio</a></li>
                
                {% if user.is_authenticated %}
                    {% if user.is_admin %}
                        <li><a href="/agregar/">Agregar producto</a></li>
                        <li><a href="/crear_categoria/">Crear categoria</a></li>
                    {% endif %}
                    <li><a href="/productos/">Productos</a></li>
                    <li><a href="/logout/">Cerrar sesión</a></li>
                {% else %}
                    <li><a href="/login/">Iniciar sesión</a></li>
                    <li><a href="/registrar/">Registrarse</a></li>
                    <li><a href="/productos/">Productos</a></li>
                    
                {% endif %}
                
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
            
        {% endblock %}
    </main>

    <footer>
        <p>© 2024 Florería. Todos los derechos reservados.</p>
    </footer>
</body>
</html>

floreria/templates/borrar_producto.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f9f9f9;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 50px auto;
        background: #ffffff;
        border: 1px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    .header {
        background-color: #ff6b6b;
        color: #ffffff;
        padding: 15px;
        text-align: center;
        border-radius: 8px 8px 0 0;
        font-size: 20px;
        font-weight: bold;
    }

    .content {
        text-align: center;
        margin: 20px 0;
        font-size: 16px;
    }

    .content strong {
        color: #333333;
    }

    .footer {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-top: 20px;
    }

    .btn {
        padding: 10px 20px;
        font-size: 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
    }

    .btn-danger {
        background-color: #ff6b6b;
        color: #ffffff;
    }

    .btn-danger:hover {
        background-color: #e63946;
    }

    .btn-secondary {
        background-color: #cccccc;
        color: #333333;
    }

    .btn-secondary:hover {
        background-color: #b3b3b3;
    }
</style>
<div class="container">
    <div class="header">
        Confirmar eliminación
    </div>
    <div class="content">
        <p>
            ¿Estás seguro de que quieres borrar el producto <strong>"{{ producto.nombre }}"</strong>?
        </p>
        <p style="color: #888;">Esta acción no se puede deshacer.</p>
    </div>
    <div class="footer">
        <form method="POST" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Sí, borrar</button>
        </form>
        <a href="{% url 'listar_productos' %}" class="btn btn-secondary">Cancelar</a>
    </div>
</div>
{% endblock %}

floreria/templates/crear_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2>Crear Nueva Categoría</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

floreria/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Inicio - Florería
{% endblock %}

{% block content %}
<style>
    body {
        background-image: url("{% static 'images/fondo.jpg' %}");
        background-size: cover;
        background-attachment: fixed;
        color: #fff;
        text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.7);
        font-family: Arial, sans-serif;
    }

    .content {
        background-color: rgba(145, 142, 142, 0.6);
        padding: 20px;
        border-radius: 10px;
        max-width: 800px;
        margin: 50px auto;
        text-align: justify;
    }

    h2 {
        font-size: 2.5em;
        margin-bottom: 20px;
    }

    p {
        font-size: 1.2em;
        line-height: 1.6;
    }
</style>

<div class="content">
    <h2>Beneficios de Tener Plantas</h2>
    <p>Las plantas no solo embellecen nuestros espacios, sino que también ofrecen una variedad de beneficios para los seres vivos:</p>
    <ul>
        <li><strong>Mejoran la calidad del aire:</strong> Las plantas absorben dióxido de carbono y liberan oxígeno, ayudando a purificar el ambiente.</li>
        <li><strong>Reducen el estrés:</strong> Estudios demuestran que rodearse de naturaleza o cuidar plantas tiene un efecto calmante y reduce los niveles de ansiedad.</li>
        <li><strong>Promueven la salud mental:</strong> Tener plantas en casa o en el trabajo fomenta la creatividad, el enfoque y la tranquilidad.</li>
        <li><strong>Regulan la humedad:</strong> Las plantas liberan vapor de agua, contribuyendo a mantener un equilibrio saludable en la humedad del aire.</li>
        <li><strong>Fomentan la biodiversidad:</strong> Ayudan a mantener ecosistemas saludables, ofreciendo refugio y alimento a pequeños animales e insectos.</li>
    </ul>
    <p>¡Explora nuestra selección y encuentra las plantas perfectas para transformar tu espacio en un oasis de vida!</p>
</div>
{% endblock %}

floreria/templates/listar_productos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.btn {
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    text-decoration: none;
    display: inline-block;
}

.btn-danger {
    background-color: #ff0000;
    color: #ffffff;
}

.btn-success {
    background-color: green;;
    color: #ffffff;
}
</style>
<div class="container123">
    <h1>Lista de Productos</h1>
    <div class="productos-grid">
        {% for producto in productos %}
        <div class="producto-card">
            <h3>{{ producto.nombre }}</h3>
            <p>Descripción: {{ producto.descripcion }}</p>
            <p>Categoría: {{ producto.categoria}}</p>
            <p>Precio: ${{ producto.precio }}</p>
            {% if producto.imagen %}
            <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" class="producto-imagen" width="200px">
            {% endif %}
            {% if user.is_authenticated %}
            {% if user.is_admin %}
            <p><a href="{% url 'borrar_producto' producto.id %}" class="btn btn-danger">Borrar</a></p>
            {% endif %}
            {% endif %}
        </div>
        {% endfor %}
        <div>
            {% if user.is_authenticated %}
            <p><a href="{% url 'exportar_excel' %}" class="btn btn-success" style="margin-left: 245%;">Exportar a Excel</a></p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

floreria/templates/login_cliente.html
{% extends 'base.html' %}

{% block content %}
<h2>Iniciar sesión</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Iniciar sesión</button>
</form>
{% endblock %}

floreria/templates/registrar_cliente.html
{% extends 'base.html' %}

{% block content %}
<h2 style="text-align: center;">Registro de Cliente</h2>
<form method="POST" class="form-registro">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="{{ form.nombre.id_for_label }}">Nombre</label>
        {{ form.nombre }}
    </div>

    <div class="form-group">
        <label for="{{ form.apellido.id_for_label }}">Apellido</label>
        {{ form.apellido }}
    </div>

    <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Correo electrónico</label>
        {{ form.email }}
    </div>

    <div class="form-group">
        <label for="{{ form.direccion.id_for_label }}">Dirección</label>
        {{ form.direccion }}
    </div>

    <div class="form-group">
        <label for="{{ form.telefono.id_for_label }}">Teléfono</label>
        {{ form.telefono }}
    </div>

    <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Contraseña</label>
        {{ form.password }}
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Registrar</button>
    </div>
</form>
{% endblock %}